### ISSUE TITLE
Operator trips over provided super-user secret

### ISSUE THREAD

**Issue by wkulhanek** [quay/quay-operator#27]
When creating a superuser secret:
oc create secret generic quay-superuser-secret --from-literal=superuser-username=test --from-literal=superuser-password=test --from-literal=superuser-email=rhpds-admins@redhat.com

And specifying that in the Quay CR:

apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quay
spec:
  quay:
    imagePullSecretName: quay-pull-secret
    superuserCredentialsName: quay-superuser-secret
    configSecretName: quay-config-secret
    database:
      volumeSize: 50Gi
    registryStorage:
      local:
        persistentVolumeAccessMode:
          - ReadWriteOnce
        persistentVolumeSize: 50Gi

The following error occurs:
{"level":"info","ts":1564163861.5151386,"logger":"controller_quayecosystem","msg":"Reconciling QuayEcosystem","Request.Namespace":"quay","Request.Name":"quay"}
{"level":"error","ts":1564163861.5152035,"logger":"controller_quayecosystem","msg":"Secret Validation","Namespace":"quay","Name":"quay-superuser-secret","error":"Failed to validate provided secret with required parameters","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/travis/gopath/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\ngithub.com/redhat-cop/quay-operator/pkg/controller/quayecosystem/validation.validateSecret\n\t/home/travis/gopath/src/github.com/redhat-cop/quay-operator/pkg/controller/quayecosystem/validation/validate.go:198\ngithub.com/redhat-cop/quay-operator/pkg/controller/quayecosystem/validation.Validate\n\t/home/travis/gopath/src/github.com/redhat-cop/quay-operator/pkg/controller/quayecosystem/validation/validate.go:25\ngithub.com/redhat-cop/quay-operator/pkg/controller/quayecosystem.(*ReconcileQuayEcosystem).Reconcile\n\t/home/travis/gopath/src/github.com/redhat-cop/quay-operator/pkg/controller/quayecosystem/quayecosystem_controller.go:127\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/travis/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.10/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.0.0-20181127025237-2b1284ed4c93/pkg/util/wait/wait.go:88"}

Also in the CR:
  status:
    conditions:
    - lastTransitionTime: "2019-07-26T17:56:49Z"
      lastUpdateTime: "2019-07-26T17:56:49Z"
      message: Configuration Updated Successfully
      status: "True"
      type: UpdateDefaultConfigurationSuccess
    - lastTransitionTime: "2019-07-26T17:56:49Z"
      lastUpdateTime: "2019-07-26T17:57:41Z"
      message: 'Failed to validate provided secret with required parameters. Namespace:
        quay, Name: quay-superuser-secret'
      reason: ProcessingError
      status: "False"
      type: QuayEcosystemValidationFailure

**Comment by wkulhanek** [comment]
Same with Config Secret

**Comment by stencell** [comment]
I ran into this the other day when I was testing, but never got around to opening an issue. For the SuperUser, you need to use:

`superuserCredentialsSecretName`

This might just be a docs bug. I didn't get a chance to run into the problem with config secret. That looks like it should be okay, but I don't know if the validation maybe failed on your config secret content vs the name?

https://github.com/redhat-cop/quay-operator/blob/master/pkg/controller/quayecosystem/validation/validate.go#L22-L57

**Comment by sabre1041** [comment]
@stencell @wkulhanek Wanted to add a few comments related to this issue. PR #29 was submitted and merged to help address them. Some of the highlights:

1. Quay requires a superuser password of at least 8 characters. Added new validation that checks this after resource creation
2. Setup error handling was not properly implemented. Even though an error occurred during the setup process, the provisioning process continued to deploy Quay. Since setup failed, due to internal validation, the secret that is generated after the setup process completes successfully was not generated.
3.  The `superuserCredentialsSecretName` was not mapped properly on the `QuayEcosystem` object. This has been corrected
4. A complete rewrite of how registry storage is managed was previously completed in order to eventually support fully defining replication scenarios. README was out of date #30 submitted to address this

I would like to push our a new tag for the repository that will provide a stable baseline prior to integrating clair. Looking to do it this week after additional community testing

**Comment by wkulhanek** [comment]
Fixed.
