### ISSUE TITLE
Quay pod does not come up with v0.0.7 image - CrashLoopBackoff 

### ISSUE THREAD

**Issue by daufinsyd** [quay/quay-operator#86]
I created a new quay instance (0.0.7 from the OpenShift Operator Hub - 4.2) and the quay pod was crash looping with the following error:
`
cp: cannot create regular file ‘/etc/pki/ca-trust/source/anchors/mitm.crt’: Permission denied
`

After applying the fix given in this issue #60:

`
 oc adm policy remove-scc-from-user anyuid system:serviceaccount:quay-enterprise:default
`
The pod could progress to the running state.

**Comment by sabre1041** [comment]
@daufinsyd the operator does not add the default service account to the `anyuid` scc. did you perform that step yourself?

**Comment by sabre1041** [comment]
@daufinsyd no. the assets that are compiled into the tagged release are the assets that are used on operator-hub. I have deployed it in multiple OpenShift clusters without issues. What i can recommend is to attempt another fresh installation if you can. Otherwise, I'd like to find time where we might be able to collaboratively debug to find a conclusive resolution

**Comment by daufinsyd** [comment]
@sabre1041 I certainly must have issued some command which led to this situation which I can't remember. Sorry for the issue.
